# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake

# The command to remove a file.
RM = /tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/smartssd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/smartssd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/smartssd/CMakeFiles /mnt/smartssd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/smartssd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compress

# Build rule for target.
compress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compress
.PHONY : compress

# fast build rule for target.
compress/fast:
	$(MAKE) -f kernel/CMakeFiles/compress.dir/build.make kernel/CMakeFiles/compress.dir/build
.PHONY : compress/fast

#=============================================================================
# Target rules for targets named xf_compress

# Build rule for target.
xf_compress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xf_compress
.PHONY : xf_compress

# fast build rule for target.
xf_compress/fast:
	$(MAKE) -f kernel/CMakeFiles/xf_compress.dir/build.make kernel/CMakeFiles/xf_compress.dir/build
.PHONY : xf_compress/fast

#=============================================================================
# Target rules for targets named xf_packer

# Build rule for target.
xf_packer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xf_packer
.PHONY : xf_packer

# fast build rule for target.
xf_packer/fast:
	$(MAKE) -f kernel/CMakeFiles/xf_packer.dir/build.make kernel/CMakeFiles/xf_packer.dir/build
.PHONY : xf_packer/fast

#=============================================================================
# Target rules for targets named xf_uncompress

# Build rule for target.
xf_uncompress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xf_uncompress
.PHONY : xf_uncompress

# fast build rule for target.
xf_uncompress/fast:
	$(MAKE) -f kernel/CMakeFiles/xf_uncompress.dir/build.make kernel/CMakeFiles/xf_uncompress.dir/build
.PHONY : xf_uncompress/fast

#=============================================================================
# Target rules for targets named xf_unpacker

# Build rule for target.
xf_unpacker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xf_unpacker
.PHONY : xf_unpacker

# fast build rule for target.
xf_unpacker/fast:
	$(MAKE) -f kernel/CMakeFiles/xf_unpacker.dir/build.make kernel/CMakeFiles/xf_unpacker.dir/build
.PHONY : xf_unpacker/fast

#=============================================================================
# Target rules for targets named compression-host

# Build rule for target.
compression-host: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compression-host
.PHONY : compression-host

# fast build rule for target.
compression-host/fast:
	$(MAKE) -f host/CMakeFiles/compression-host.dir/build.make host/CMakeFiles/compression-host.dir/build
.PHONY : compression-host/fast

#=============================================================================
# Target rules for targets named compression-client

# Build rule for target.
compression-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compression-client
.PHONY : compression-client

# fast build rule for target.
compression-client/fast:
	$(MAKE) -f client/CMakeFiles/compression-client.dir/build.make client/CMakeFiles/compression-client.dir/build
.PHONY : compression-client/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... xf_compress"
	@echo "... xf_packer"
	@echo "... xf_uncompress"
	@echo "... xf_unpacker"
	@echo "... compress"
	@echo "... compression-host"
	@echo "... compression-client"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

